name = "wheel-collectors-api"
main = "src/index.ts"
compatibility_date = "2024-03-15"

[vars]
JWT_SECRET = "toy-project-secret-123"

[[d1_databases]]
binding = "DB"
database_name = "wheel-collectors-db"
database_id = "bb63dc2c-5d49-4d16-8ee7-23b24df5ec2a"


