name = "wheelcollectorsz"
main = "src/index.ts"
compatibility_date = "2024-03-15"

[vars]
JWT_SECRET = "toy-project-secret-123"
RAZORPAY_KEY_ID = "rzp_live_SS08BJzv05lh7z"
RAZORPAY_KEY_SECRET = "Q6HIoJIAMYa1466eQ7nnmxqX"

[[d1_databases]]
binding = "DB"
database_name = "wheelcollectorsz-db"
database_id = "1d346fde-f7af-491c-aa20-1b45020bf24a"


